//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRBL_Plotter.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRBL_Plotter.Resources.ResStrings", typeof(ResStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alarm.
        /// </summary>
        public static string grblAlarm {
            get {
                return ResourceManager.GetString("grblAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        public static string grblCheck {
            get {
                return ResourceManager.GetString("grblCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Door.
        /// </summary>
        public static string grblDoor {
            get {
                return ResourceManager.GetString("grblDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hold.
        /// </summary>
        public static string grblHold {
            get {
                return ResourceManager.GetString("grblHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string grblHome {
            get {
                return ResourceManager.GetString("grblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Idle.
        /// </summary>
        public static string grblIdle {
            get {
                return ResourceManager.GetString("grblIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jog.
        /// </summary>
        public static string grblJog {
            get {
                return ResourceManager.GetString("grblJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probe.
        /// </summary>
        public static string grblProbe {
            get {
                return ResourceManager.GetString("grblProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string grblRun {
            get {
                return ResourceManager.GetString("grblRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sleep.
        /// </summary>
        public static string grblSleep {
            get {
                return ResourceManager.GetString("grblSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        public static string mainAttention {
            get {
                return ResourceManager.GetString("mainAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feel free to improove translation.
        /// </summary>
        public static string mainHelpLanguage {
            get {
                return ResourceManager.GetString("mainHelpLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File &apos;hotkeys.xml&apos; not found, no hotkeys set!.
        /// </summary>
        public static string mainHotkeyError {
            get {
                return ResourceManager.GetString("mainHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown action:.
        /// </summary>
        public static string mainHotkeyError1 {
            get {
                return ResourceManager.GetString("mainHotkeyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error with Hotkey.xml.
        /// </summary>
        public static string mainHotkeyError2 {
            get {
                return ResourceManager.GetString("mainHotkeyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check G-Code.
        /// </summary>
        public static string mainInfoCheckCode {
            get {
                return ResourceManager.GetString("mainInfoCheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error before line.
        /// </summary>
        public static string mainInfoErrorLine {
            get {
                return ResourceManager.GetString("mainInfoErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish checking G-Code.
        /// </summary>
        public static string mainInfoFinishCheck {
            get {
                return ResourceManager.GetString("mainInfoFinishCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish sending G-Code.
        /// </summary>
        public static string mainInfoFinishSend {
            get {
                return ResourceManager.GetString("mainInfoFinishSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;Kill Alarm&apos; to proceed (&apos;$X&apos;).
        /// </summary>
        public static string mainInfoKill {
            get {
                return ResourceManager.GetString("mainInfoKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laser Mode not active $32=0.
        /// </summary>
        public static string mainInfoLaserModeOff {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laser Mode active $32=1.
        /// </summary>
        public static string mainInfoLaserModeOn {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause streaming - press play (.
        /// </summary>
        public static string mainInfoPause {
            get {
                return ResourceManager.GetString("mainInfoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probing.
        /// </summary>
        public static string mainInfoProbing {
            get {
                return ResourceManager.GetString("mainInfoProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;Resume&apos; to proceed (&apos;~&apos;).
        /// </summary>
        public static string mainInfoResume {
            get {
                return ResourceManager.GetString("mainInfoResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send G-Code.
        /// </summary>
        public static string mainInfoSendCode {
            get {
                return ResourceManager.GetString("mainInfoSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STOP streaming (.
        /// </summary>
        public static string mainInfoStopStream {
            get {
                return ResourceManager.GetString("mainInfoStopStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STOP streaming ( Line.
        /// </summary>
        public static string mainInfoStopStream2 {
            get {
                return ResourceManager.GetString("mainInfoStopStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool change....
        /// </summary>
        public static string mainInfoToolChange {
            get {
                return ResourceManager.GetString("mainInfoToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo last action.
        /// </summary>
        public static string mainInfoUndo {
            get {
                return ResourceManager.GetString("mainInfoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait for IDLE, then pause (.
        /// </summary>
        public static string mainInfoWaitIdle {
            get {
                return ResourceManager.GetString("mainInfoWaitIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next move will exceed machine limits!\r.
        /// </summary>
        public static string mainLimits1 {
            get {
                return ResourceManager.GetString("mainLimits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \r\n Press &apos;Ok&apos; to move anyway.
        /// </summary>
        public static string mainLimits2 {
            get {
                return ResourceManager.GetString("mainLimits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphics dimension exceeds machine dimension!\r\nTransformation is recommended to avoid damaging the machine!.
        /// </summary>
        public static string mainLimits3 {
            get {
                return ResourceManager.GetString("mainLimits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streaming must be stopped before loading new file.
        /// </summary>
        public static string mainLoadError {
            get {
                return ResourceManager.GetString("mainLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File not found: &apos;.
        /// </summary>
        public static string mainLoadError1 {
            get {
                return ResourceManager.GetString("mainLoadError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL extension is not &apos;svg&apos; or &apos;dxf&apos;\r\nTry SVG import anyway, but without setting &apos;Recent File&apos; list..
        /// </summary>
        public static string mainLoadError2 {
            get {
                return ResourceManager.GetString("mainLoadError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File extension not supported &apos;.
        /// </summary>
        public static string mainLoadError3 {
            get {
                return ResourceManager.GetString("mainLoadError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not a valid number.
        /// </summary>
        public static string mainParseError {
            get {
                return ResourceManager.GetString("mainParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not a valid number, set line to 0.
        /// </summary>
        public static string mainParseError1 {
            get {
                return ResourceManager.GetString("mainParseError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause streaming - press play.
        /// </summary>
        public static string mainPauseStream {
            get {
                return ResourceManager.GetString("mainPauseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The last job was paused at line.
        /// </summary>
        public static string mainPauseStream1 {
            get {
                return ResourceManager.GetString("mainPauseStream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ,\r\ndo you want to continue the job?.
        /// </summary>
        public static string mainPauseStream2 {
            get {
                return ResourceManager.GetString("mainPauseStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem.
        /// </summary>
        public static string mainProblem {
            get {
                return ResourceManager.GetString("mainProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progress.
        /// </summary>
        public static string mainProgress {
            get {
                return ResourceManager.GetString("mainProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit GRBL-Plotter?.
        /// </summary>
        public static string mainQuit {
            get {
                return ResourceManager.GetString("mainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        public static string mainSimuSpeed {
            get {
                return ResourceManager.GetString("mainSimuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start path simulation.
        /// </summary>
        public static string mainSimuStart {
            get {
                return ResourceManager.GetString("mainSimuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop simulation.
        /// </summary>
        public static string mainSimuStop {
            get {
                return ResourceManager.GetString("mainSimuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streaming is still active - press Stop and try again.
        /// </summary>
        public static string mainStreamingActive {
            get {
                return ResourceManager.GetString("mainStreamingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool / Pen change!.
        /// </summary>
        public static string mainToolChange {
            get {
                return ResourceManager.GetString("mainToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool change needed:\r.
        /// </summary>
        public static string mainToolChange1 {
            get {
                return ResourceManager.GetString("mainToolChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \rpress start to continue..
        /// </summary>
        public static string mainToolChange2 {
            get {
                return ResourceManager.GetString("mainToolChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed some unknown G-Code:\r\n.
        /// </summary>
        public static string mainUnknownCode {
            get {
                return ResourceManager.GetString("mainUnknownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probing canceled.
        /// </summary>
        public static string probingCancel1 {
            get {
                return ResourceManager.GetString("probingCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process last command.
        /// </summary>
        public static string probingCancel2 {
            get {
                return ResourceManager.GetString("probingCancel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to center.
        /// </summary>
        public static string probingCenter {
            get {
                return ResourceManager.GetString("probingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail: no contact.
        /// </summary>
        public static string probingFail1 {
            get {
                return ResourceManager.GetString("probingFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel probing.
        /// </summary>
        public static string probingFail2 {
            get {
                return ResourceManager.GetString("probingFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string probingFinish {
            get {
                return ResourceManager.GetString("probingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probing on.
        /// </summary>
        public static string probingProbingOn {
            get {
                return ResourceManager.GetString("probingProbingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set center .
        /// </summary>
        public static string probingSetCenter {
            get {
                return ResourceManager.GetString("probingSetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time out.
        /// </summary>
        public static string probingTimeOut {
            get {
                return ResourceManager.GetString("probingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string serialClose {
            get {
                return ResourceManager.GetString("serialClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serial Connection is needed.\r\nClose main window instead.
        /// </summary>
        public static string serialCloseError {
            get {
                return ResourceManager.GetString("serialCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string serialOpen {
            get {
                return ResourceManager.GetString("serialOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check COM-window for further information.
        /// </summary>
        public static string statusStripeCheckCOM {
            get {
                return ResourceManager.GetString("statusStripeCheckCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;Check for new GRBL-Plotter release on GitHub&apos; - can be disabled in [Setup - Program control] .
        /// </summary>
        public static string statusStripeCheckUpdate {
            get {
                return ResourceManager.GetString("statusStripeCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control-Click to select Figure; Alt-Click to select Group; Or click on XML-Tag.
        /// </summary>
        public static string statusStripeClickKeys {
            get {
                return ResourceManager.GetString("statusStripeClickKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click: mark Figure; Control-Click: mark Group; Alt-Click: show GCode line.
        /// </summary>
        public static string statusStripeClickKeys2 {
            get {
                return ResourceManager.GetString("statusStripeClickKeys2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control-Down to move selected Block one down; Control-Shift-Down to move to end.
        /// </summary>
        public static string statusStripeDownKeys {
            get {
                return ResourceManager.GetString("statusStripeDownKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit mode on - click into 2D view to finish.
        /// </summary>
        public static string statusStripeEditModeOn {
            get {
                return ResourceManager.GetString("statusStripeEditModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File loading.
        /// </summary>
        public static string statusStripeFileLoad {
            get {
                return ResourceManager.GetString("statusStripeFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File not found - remove from list.
        /// </summary>
        public static string statusStripeFileNotFound {
            get {
                return ResourceManager.GetString("statusStripeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perhaps serial port is locked and a restart of GRBL-Plotter is needed.
        /// </summary>
        public static string statusStripeGrblResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeGrblResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probably a reset of the controller is needed.
        /// </summary>
        public static string statusStripeResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection moved by.
        /// </summary>
        public static string statusStripeSelectionMoved {
            get {
                return ResourceManager.GetString("statusStripeSelectionMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Streaming status and G-Code are saved in &apos;_lastProcessed.nc&apos;. Continuation after program restart is possible..
        /// </summary>
        public static string statusStripeStreamingStatusSaved {
            get {
                return ResourceManager.GetString("statusStripeStreamingStatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control-Up to move selected Block one up; Control-Shift-Up to move to top.
        /// </summary>
        public static string statusStripeUpKeys {
            get {
                return ResourceManager.GetString("statusStripeUpKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
